import {
  SapphireClient,
  ApplicationCommandRegistries,
  LogLevel,
} from '@sapphire/framework';
import '@sapphire/plugin-scheduled-tasks/register';
import '@kaname-png/plugin-subcommands-advanced/register';
import { GatewayIntentBits } from 'discord.js';

const client = new SapphireClient({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.GuildMembers,
    GatewayIntentBits.GuildScheduledEvents,
  ],
  logger: {
    level: process.env.NODE_ENV === 'development' ? LogLevel.Debug : LogLevel.Info,
  },
  tasks: { bull: { connection: { host: process.env.redisHost } } },
  subcommandsAdvanced: { nameCommandsAutogenerated: true },
});

// TODO: Register all commands at Discord first. So we get all idHints
if (process.env.NODE_ENV === 'development')
  ApplicationCommandRegistries.setDefaultGuildIds([String(process.env.devGuild)]);

// discord connect
await client.login(process.env.DCtoken);
